name: Android CI/CD
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code
                uses: actions/checkout@v3

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Grant execute permissions for gradlew
                run: chmod +x gradlew

            -   name: Run ktlint
                run: ./gradlew ktlintCheck

            -   name: Run unit tests
                run: ./gradlew testDebugUnitTest

            -   name: Build APK
                run: ./gradlew assembleDebug

            -   name: Upload APK
                uses: actions/upload-artifact@v4
                with:
                    name: debug-apk
                    path: app/build/outputs/apk/debug/app-debug.apk
